AssetManagementWEBjm/AssetManagementWEBjm/Controllers/AssetController.cs
using AssetManagementWEBjm.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using AssetManagementWEBjm.Models;
using AssetManagementWEBjm.Database;
using System.Globalization;
using AssetManagementWEBjm.Controllers;

namespace AssetManagementWEBjm.Controllers
{
    public class AssetController : Controller
    {
        // GET: Asset
        public ActionResult Index() //Rutiinin nimi
        {
            return View();
        }

        #region //Test
   
        //AssetController.cs - testilaukseen luominen scriptin siirtoa varten:
        //Tämä testilauseke voidaan laittaa privaatiksi, kun kaikki on valmista:

        //Paina Test rivillä hiiren oikealla ja valitse Add View...Empty
        public ActionResult Test()
        { 
        List<LocatedAssetsViewModel> model = new List<LocatedAssetsViewModel>();

        JohaMeriSQL1Entities entities = new JohaMeriSQL1Entities();
            try
            {
                List<AssetLocations> assets = entities.AssetLocations.ToList();

                CultureInfo fiFi = new CultureInfo("fi-FI");

                // muodostetaan näkymämalli tietokannan rivien pohjalta
                foreach (AssetLocations asset in assets)
                {
                    LocatedAssetsViewModel view = new LocatedAssetsViewModel();
                    view.Id = asset.Id;
                    view.LocationCode = asset.AssetLocation.Code;
                    view.LocationName = asset.AssetLocation.Name;
                    view.LocationAdress = asset.AssetLocation.Adress;
                    view.AssetCode = asset.Assets.Code;
                    view.AssetName = asset.Assets.Type + ": " + asset.Assets.Model;
                    //view.LastSeen = asset.LastSeen.Value.ToString(fiFi);
                    view.LastSeen = asset.LastSeen.GetValueOrDefault();         
                    //view.LastSeen = asset.LastSeen;

                    model.Add(view);
                }
            }
            finally
            {
                entities.Dispose();
            }

            return View(model);
        }

        #endregion

        //tehdään listaus kaikista kytkennöistä
        public ActionResult List()
        {
            List<LocatedAssetsViewModel> model = new List<LocatedAssetsViewModel>();

            //Tietokantayhteys:
            JohaMeriSQL1Entities entities = new JohaMeriSQL1Entities();
            try
            {
                List<AssetLocations> assets = entities.AssetLocations.ToList();

                CultureInfo fiFi = new CultureInfo("fi-FI");

                // muodostetaan näkymämalli tietokannan rivien pohjalta
                foreach (AssetLocations asset in assets)
                {
                    //mallia käytetään käyttöliittymään:
                    //kopioidaan nimet toisesta objektista toiseen objektiin:
                    LocatedAssetsViewModel view = new LocatedAssetsViewModel();
                    view.Id = asset.Id;
                    view.LocationCode = asset.AssetLocation.Code;
                    view.LocationName = asset.AssetLocation.Name;
                    view.LocationAdress = asset.AssetLocation.Adress;
                    view.AssetCode = asset.Assets.Code;
                    view.AssetName = asset.Assets.Type + ": " + asset.Assets.Model;
                    //view.LastSeen = asset.LastSeen.Value.ToString(fiFi);
                    //view.LastSeen = asset.LastSeen.Value.ToString("dd-MM-yyyy");
                    view.LastSeen = asset.LastSeen.GetValueOrDefault();

                    model.Add(view);
                }
            }
            finally
            {
                entities.Dispose();
            }

            return View(model);
        }
        //ks.DateTime   https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

        public ActionResult ListJson()
        {
            List<LocatedAssetsViewModel> model = new List<LocatedAssetsViewModel>();

            JohaMeriSQL1Entities entities = new JohaMeriSQL1Entities();
            try
            {
                List<AssetLocations> assets = entities.AssetLocations.ToList();

                CultureInfo fiFi = new CultureInfo("fi-FI");
                
                // muodostetaan näkymämalli tietokannan rivien pohjalta
                foreach (AssetLocations asset in assets)
                {
                    LocatedAssetsViewModel view = new LocatedAssetsViewModel();
                    view.Id = asset.Id;
                    view.LocationCode = asset.AssetLocation.Code;
                    view.LocationName = asset.AssetLocation.Name;
                    view.AssetCode = asset.Assets.Code;
                    view.AssetName = asset.Assets.Type + ": " + asset.Assets.Model;
                    //view.LastSeen = asset.LastSeen.Value.ToString(fiFi);
                    view.LastSeen = asset.LastSeen.GetValueOrDefault();

                    model.Add(view);
                }
            }
            finally
            {
                entities.Dispose();
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }
 
        [HttpPost]
        //AssetController.cs - LAITTEIDEN TALLENTAMINEN (SQL) TIETOKANTAAN
        public JsonResult AssignLocation()
        {
            string json = Request.InputStream.ReadToEnd(); //WebUtilities -luokka, laajennusmetodi
            AssignLocationModel inputData = 
                JsonConvert.DeserializeObject<AssignLocationModel>(json);

            bool success = false;
            string error = "";

            JohaMeriSQL1Entities entities = new JohaMeriSQL1Entities();

            try
            {
                //haetaan ensin paikan id-numero koodin perusteella:
                int locationId = (from l in entities.AssetLocation
                    where l.Code == inputData.LocationCode
                    select l.Id).FirstOrDefault();

                //haetaan laitteen id-numero koodin perusteella:
                int assetId = (from a in entities.Assets
                                  where a.Code == inputData.AssetCode
                                  select a.Id).FirstOrDefault();

                if ((locationId > 0) && (assetId > 0))
                {
                    //tallennetaan uusi rivi aikaleiman kanssa kantaan:
                    AssetLocations newEntry = new AssetLocations();
                    newEntry.LocationId = locationId;
                    newEntry.AssetId = assetId;
                    newEntry.LastSeen = DateTime.Now;

                    entities.AssetLocations.Add(newEntry);

                    entities.SaveChanges();

                    success = true;
                }
            }
            catch (Exception ex)
            {
                error = ex.GetType().Name + ": " + ex.Message;
            }
            finally
            {
                entities.Dispose();
            }

            //palautetaan JSON-muotoinen tulos kutsujalle
            var result = new { success = success, error = error };
            return Json(result);
        }

        #region //create
        // GET: Asset/CreateAssets
        public ActionResult CreateAssets()
        {
            JohaMeriSQL1Entities db = new JohaMeriSQL1Entities();

            AssetsViewModel model = new AssetsViewModel();

            return View(model);
        }//create


        // POST:  Asset/CreateAssets
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAssets(AssetsViewModel model)
        {
            JohaMeriSQL1Entities db = new JohaMeriSQL1Entities();

            Assets asset = new Assets();
            asset.Code = model.AssetCode;
            asset.Type = model.AssetType;
            asset.Model = model.AssetModel;
            
            db.Assets.Add(asset);

            //AssetLocation ass = new AssetLocation();
            //ass.Code = model.LocationCode;
            //ass.Name = model.LocationName;
            //ass.Adress = model.LocationAdress;

            //db.AssetLocation.Add(ass);

            //int assetId = int.Parse(model.AssetCode);
            //if (assetId > 0)
            //{
            //    Assets asse = db.Assets.Find(assetId);
            //    ass.AssetId = asse.Id;
            //}

            //int assettypId = int.Parse(model.AssetType);
            //if (assetId > 0)
            //{
            //    Assets asse = db.Assets.Find(assettypId);
            //    ass.AssetId = asse.Id;
            //}

            //int assetmodId = int.Parse(model.AssetModel);
            //if (assetId > 0)
            //{
            //    Assets asse = db.Assets.Find(assetmodId);
            //    ass.AssetId = asse.Id;
            //}

            //int locationId = int.Parse(model.LocationCode);
            //if (locationId > 0)
            //{
            //    AssetLocation alo = db.AssetLocation.Find(locationId);
            //    asset.Id = alo.Id;
            //}

            //int locationcodId = int.Parse(model.LocationName);
            //if (locationcodId > 0)
            //{
            //    AssetLocation asse = db.AssetLocation.Find(locationcodId);
            //    asset.Id = asse.Id;
            //}

            //int locationadId = int.Parse(model.LocationAdress);
            //if (locationadId > 0)
            //{
            //    AssetLocation asse = db.AssetLocation.Find(locationadId);
            //    asset.Id = asse.Id;
            //}

            try
            {
                db.SaveChanges();
            }

            catch (Exception ex)
            {
            }

            return RedirectToAction("List");
        }//create

AssetManagementWEBjm/AssetManagementWEBjm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Asset Management</title>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("head", required: false)

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-2.2.4.js"></script>
    <script src="~/Scripts/respond.js"></script>
    @*<script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>*@
 

    @*<script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"1a0213e6-e58b-46ec-83e0-4489b56725a5"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>*@
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" aria-expanded="false" aria-controls="navbarsExampleDefault" aria-label="Toggle navigation" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="~/Home/Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="dropdown01" aria-expanded="false" aria-haspopup="true" href="http://example.com" data-toggle="dropdown">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="~/Asset/List">List</a>
                        <a class="dropdown-item" href="~/Asset/ListJson">ListJson</a>
                        <a class="dropdown-item" href="~/Asset/Test">Test</a>
                        <a class="dropdown-item" href="~/Asset/AssetsList">AssetsList</a>
                        <a class="dropdown-item" href="~/Asset/AssetLocationList">AssetLocationList</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" aria-label="Search" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>


    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("List", "List", "Asset")</li>
                    <li>@Html.ActionLink("ListJson", "ListJson", "Asset")</li>
                    <li>@Html.ActionLink("Test", "Test", "Asset")</li>
                    <li>@Html.ActionLink("AssetsList", "AssetsList", "Asset")</li>
                    <li>@Html.ActionLink("AssetLocationList", "AssetLocationList", "Asset")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Point Asset Management</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>